# Generated by Erlang.mk. Edit at your own risk!

src/homework6.erl:: src/my_cache.erl; @touch $@
src/homework6_handler.erl:: src/homework6.erl src/my_cache.erl; @touch $@

COMPILE_FIRST += my_cache homework6
